apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dev-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        name: dev-triggertemplate

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: dev-event-listener
  name: el-main-trigger-route
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-dev-event-listener
    weight: null
